import { useState } from 'react'
import { App, Button, Card, Form, Input, InputNumber, Modal, Popconfirm, Space, Table, Tag, Typography } from 'antd'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createCategory, listAllCategories, setCategoryStatus, updateCategory, type Category } from '../api/catalog'

export default function CategoryPage(){
  const {message}=App.useApp();const client=useQueryClient();const query=useQuery({queryKey:['categories','all'],queryFn:listAllCategories});const [editing,setEditing]=useState<Category|null|undefined>(undefined);const [form]=Form.useForm();
  const save=useMutation({mutationFn:async()=>{const values=await form.validateFields();return editing?updateCategory(editing.id,values):createCategory(values)},onSuccess:()=>{message.success('分类已保存');setEditing(undefined);client.invalidateQueries({queryKey:['categories']})},onError:e=>message.error(e.message)});
  const status=useMutation({mutationFn:({id,value}:{id:string;value:'ACTIVE'|'DISABLED'})=>setCategoryStatus(id,value),onSuccess:()=>{message.success('分类状态已更新');client.invalidateQueries({queryKey:['categories']})},onError:e=>message.error(e.message)});
  function open(row?:Category){setEditing(row??null);form.setFieldsValue(row?{name:row.name,sortOrder:row.sortOrder}:{name:'',sortOrder:100})}
  return <Card><Space direction="vertical" size="large" style={{width:'100%'}}><Space style={{width:'100%',justifyContent:'space-between'}}><div><Typography.Title level={3} style={{margin:0}}>服务分类</Typography.Title><Typography.Text type="secondary">小程序目录和新增 SKU 的分类选项均以这里的启用分类为准</Typography.Text></div><Button type="primary" onClick={()=>open()}>新增分类</Button></Space><Table rowKey="id" loading={query.isLoading} dataSource={query.data} pagination={false} columns={[{title:'分类名称',dataIndex:'name'},{title:'排序',dataIndex:'sortOrder',width:100},{title:'SKU 数',dataIndex:'skuCount',width:100},{title:'状态',dataIndex:'status',render:v=><Tag color={v==='ACTIVE'?'green':'default'}>{v==='ACTIVE'?'启用':'停用'}</Tag>},{title:'操作',render:(_,r)=><Space><Button size="small" onClick={()=>open(r)}>编辑</Button><Popconfirm title={r.status==='ACTIVE'?'确认停用该分类？':'确认启用该分类？'} onConfirm={()=>status.mutate({id:r.id,value:r.status==='ACTIVE'?'DISABLED':'ACTIVE'})}><Button size="small" danger={r.status==='ACTIVE'}>{r.status==='ACTIVE'?'停用':'启用'}</Button></Popconfirm></Space>}]}/></Space><Modal title={editing?'编辑分类':'新增分类'} open={editing!==undefined} onCancel={()=>setEditing(undefined)} onOk={()=>save.mutate()} confirmLoading={save.isPending} destroyOnHidden><Form form={form} layout="vertical"><Form.Item name="name" label="客户端分类名称" rules={[{required:true,min:2,max:64}]}><Input placeholder="例如：精准测漏"/></Form.Item><Form.Item name="sortOrder" label="排序" rules={[{required:true}]}><InputNumber min={0} max={9999} style={{width:'100%'}}/></Form.Item></Form></Modal></Card>
}
