import { apiRequest } from './http'

export interface Worker { id: string; username: string; displayName: string; mobile: string; status: string; openWorkOrderCount: number; trades?: string[]; skills?: string[]; appointmentAvailable?: boolean }
export interface WorkOrderSummary { id: string; workOrderNo: string; orderId: string; orderNo: string; status: string; priority: string; assigneeId?: string; assigneeName?: string; appointmentAt?: string; appointmentSlot?: string; version: number; completionOutcome?: string }
export interface AdminEvidence { id: string; mediaId: string; stage: string; customerVisible: boolean; mediaType: 'IMAGE' | 'VIDEO'; contentType: string; url: string; createdAt: string }
export interface AdminInternalReview { id: string; level: 'QA' | 'DIRECTOR'; decision: 'APPROVE' | 'REJECT'; reviewerId: string; reviewerName?: string; note?: string; createdAt: string }
export interface AdminWorkOrderDetail extends WorkOrderSummary { orderId: string; serviceAddress: string; contactName: string; contactMobile: string; completionSummary?: string; reviewNote?: string; acceptedAt?: string; arrivedAt?: string; startedAt?: string; completionSubmittedAt?: string; reviewedAt?: string; finishedAt?: string; visitStatus: string; customerAcceptanceStatus: string; customerAcceptanceSource?: string; customerAcceptanceAt?: string; internalReviewStatus: string; closureStatus: string; completionOutcome?: string; completionSubmissionAt?: string; closedAt?: string; evidence: AdminEvidence[]; internalReviews: AdminInternalReview[] }
export interface TimelineEvent { code: string; operatorType: string; note?: string; createdAt: string }
export interface WorkOrderPage { items: WorkOrderSummary[]; total: number; page: number; pageSize: number }
export const listWorkers = () => apiRequest<Worker[]>('/api/v1/admin/workers?status=ACTIVE')
export interface WorkerCandidate extends Worker { matchedSkills: string[]; matchedSkillCount: number; requiredSkillCount: number; allSkillsMatched: boolean }
export const listWorkerCandidates = (workOrderId: string, tradeId = '', skillId = '') => apiRequest<WorkerCandidate[]>(`/api/v1/admin/workers/candidates?workOrderId=${workOrderId}&tradeId=${tradeId}&skillId=${skillId}`)
export const listWorkOrders = (status = '', keyword = '', completionOutcome = '', page = 1) => apiRequest<WorkOrderPage>(`/api/v1/admin/work-orders?status=${encodeURIComponent(status)}&completionOutcome=${encodeURIComponent(completionOutcome)}&keyword=${encodeURIComponent(keyword)}&page=${page}&pageSize=20`)
export const getWorkOrder = (id: string) => apiRequest<AdminWorkOrderDetail>(`/api/v1/admin/work-orders/${id}`)
export const getWorkOrderTimeline = (id: string) => apiRequest<{ items: TimelineEvent[] }>(`/api/v1/admin/work-orders/${id}/timeline`)
export const assignWorkOrder = (id: string, input: { workerId: string; note: string; version: number }) => apiRequest<{ updated: boolean }>(`/api/v1/admin/work-orders/${id}/assign`, { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ ...input, workerId: Number(input.workerId) }) })
export const reassignWorkOrder = (id: string, input: { workerId: string; appointmentAt: string; reason: string; version: number }) => apiRequest<{ updated: boolean }>(`/api/v1/admin/work-orders/${id}/reassign`, { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ ...input, workerId: Number(input.workerId) }) })
export const reviewCompletion = (id: string, input: { decision: 'APPROVE' | 'REJECT'; note: string; version: number }) => apiRequest<{ updated: boolean }>(`/api/v1/admin/work-orders/${id}/completion-review`, { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify(input) })
export const internalReview = (id: string, level: 'QA' | 'DIRECTOR', input: { decision: 'APPROVE' | 'REJECT'; note: string; version: number }) => apiRequest<{ updated: boolean }>(`/api/v1/admin/work-orders/${id}/internal-review?level=${level}`, { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify(input) })
