ALTER TABLE employee_account
    ADD COLUMN IF NOT EXISTS avatar_media_id BIGINT NULL CHECK (avatar_media_id IS NULL OR avatar_media_id >= 0);

CREATE TABLE IF NOT EXISTS worker_certificate_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    worker_id BIGINT NOT NULL CHECK (worker_id >= 0),
    media_id BIGINT NOT NULL CHECK (media_id >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_worker_certificate_media UNIQUE (org_id, worker_id, media_id)
);
CREATE INDEX IF NOT EXISTS idx_worker_certificate_media_worker ON worker_certificate_media(org_id, worker_id, created_at, id);
