ALTER TABLE employee_account
    ADD COLUMN worker_no VARCHAR(32) NULL,
    ADD COLUMN joined_on DATE NULL,
    ADD COLUMN remark VARCHAR(500) NULL,
    ADD COLUMN deleted_at TIMESTAMPTZ(3) NULL;

CREATE UNIQUE INDEX uk_employee_org_worker_no ON employee_account(org_id, worker_no) WHERE worker_no IS NOT NULL;
CREATE UNIQUE INDEX uk_employee_org_mobile ON employee_account(org_id, mobile) WHERE mobile IS NOT NULL;
CREATE INDEX idx_employee_worker_filters ON employee_account(org_id, role, status, deleted_at);

CREATE TABLE worker_trade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    trade_code VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(500) NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE(org_id, trade_code), UNIQUE(org_id, name)
);
CREATE INDEX idx_worker_trade_list ON worker_trade(org_id, status, sort_order, id);

CREATE TABLE worker_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    trade_id BIGINT NOT NULL REFERENCES worker_trade(id),
    skill_code VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(500) NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE(org_id, skill_code), UNIQUE(org_id, trade_id, name)
);
CREATE INDEX idx_worker_skill_list ON worker_skill(org_id, trade_id, status, sort_order, id);

CREATE TABLE worker_trade_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL REFERENCES employee_account(id),
    trade_id BIGINT NOT NULL REFERENCES worker_trade(id),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE(org_id, worker_id, trade_id)
);
CREATE INDEX idx_worker_trade_assignment_worker ON worker_trade_assignment(org_id, worker_id);

CREATE TABLE worker_skill_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL REFERENCES employee_account(id),
    skill_id BIGINT NOT NULL REFERENCES worker_skill(id),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE(org_id, worker_id, skill_id)
);
CREATE INDEX idx_worker_skill_assignment_worker ON worker_skill_assignment(org_id, worker_id);

CREATE TABLE service_sku_skill_requirement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL REFERENCES service_sku(id),
    skill_id BIGINT NOT NULL REFERENCES worker_skill(id),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE(org_id, sku_id, skill_id)
);
CREATE INDEX idx_sku_skill_requirement_sku ON service_sku_skill_requirement(org_id, sku_id);

CREATE TABLE worker_profile_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL REFERENCES employee_account(id),
    event_code VARCHAR(64) NOT NULL,
    operator_type VARCHAR(32) NOT NULL,
    operator_id BIGINT NOT NULL DEFAULT 0,
    operator_name VARCHAR(64) NOT NULL DEFAULT 'system',
    before_json JSONB NULL,
    after_json JSONB NULL,
    reason VARCHAR(512) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX idx_worker_profile_history ON worker_profile_history(org_id, worker_id, created_at, id);

CREATE TRIGGER trg_worker_trade_updated_at BEFORE UPDATE ON worker_trade FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_worker_skill_updated_at BEFORE UPDATE ON worker_skill FOR EACH ROW EXECUTE FUNCTION set_updated_at();

UPDATE employee_account SET status='DRAFT' WHERE role='WORKER' AND status='ACTIVE';
