CREATE TABLE customer_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    customer_id BIGINT NOT NULL CHECK (customer_id >= 0),
    city VARCHAR(64) NOT NULL,
    detail_address VARCHAR(255) NOT NULL,
    building_door VARCHAR(128) NOT NULL,
    contact_name VARCHAR(64) NOT NULL,
    contact_mobile VARCHAR(32) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE INDEX idx_customer_address_owner ON customer_address (org_id, customer_id, updated_at DESC);
CREATE UNIQUE INDEX uk_customer_address_default ON customer_address (org_id, customer_id) WHERE is_default;
CREATE TRIGGER trg_customer_address_updated_at BEFORE UPDATE ON customer_address FOR EACH ROW EXECUTE FUNCTION set_updated_at();
