-- PLAN-010: 师傅手机号登录、首次改密和独立 Worker session。

ALTER TABLE employee_account
    ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN IF NOT EXISTS last_password_changed_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN IF NOT EXISTS password_version INTEGER NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS idx_employee_worker_mobile
    ON employee_account (org_id, mobile)
    WHERE role = 'WORKER' AND deleted_at IS NULL AND mobile IS NOT NULL;

CREATE TABLE IF NOT EXISTS worker_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id > 0),
    worker_id BIGINT NOT NULL,
    token_hash BYTEA NOT NULL CHECK (octet_length(token_hash) = 32),
    password_version INTEGER NOT NULL CHECK (password_version > 0),
    expires_at TIMESTAMPTZ(3) NOT NULL,
    last_seen_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    revoked_at TIMESTAMPTZ(3) NULL,
    user_agent VARCHAR(512) NULL,
    ip_address VARCHAR(64) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_worker_session_token UNIQUE (token_hash),
    CONSTRAINT fk_worker_session_worker FOREIGN KEY (worker_id) REFERENCES employee_account(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_worker_session_worker
    ON worker_session (org_id, worker_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_worker_session_expiry
    ON worker_session (expires_at)
    WHERE revoked_at IS NULL;

-- 后台的师傅重置密码需要独立操作权限，避免只有查看或普通资料维护权限即可重置密码。
INSERT INTO admin_permission (permission_code, resource, action, permission_type, parent_code, route_path, sort_order, status)
VALUES ('worker.reset_password', 'worker', 'reset_password', 'ACTION', 'worker.view', NULL, 62, 'ACTIVE')
ON CONFLICT (permission_code) DO UPDATE
SET resource = EXCLUDED.resource,
    action = EXCLUDED.action,
    permission_type = EXCLUDED.permission_type,
    parent_code = EXCLUDED.parent_code,
    sort_order = EXCLUDED.sort_order,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP(3);

INSERT INTO admin_role_permission (org_id, role_id, permission_id)
SELECT r.org_id, r.id, p.id
FROM admin_role r
JOIN admin_permission p ON p.permission_code = 'worker.reset_password'
WHERE r.role_code = 'tenant_admin'
ON CONFLICT DO NOTHING;
