-- PLAN-009: 后台用户、角色、会话和 Casbin Domain 策略事实表。
-- 规范化关系表是唯一事实来源，授权层按 org::<org_id> 生成 Casbin Domain。

CREATE TABLE admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id > 0),
    username VARCHAR(64) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_admin_user_org_username UNIQUE (org_id, username),
    CONSTRAINT uk_admin_user_org_id UNIQUE (org_id, id),
    CONSTRAINT ck_admin_user_status CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED'))
);
CREATE INDEX idx_admin_user_org_status ON admin_user (org_id, status, created_at DESC);
CREATE TRIGGER trg_admin_user_updated_at BEFORE UPDATE ON admin_user FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE admin_user_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id > 0),
    user_id BIGINT NOT NULL,
    token_hash BYTEA NOT NULL CHECK (octet_length(token_hash) = 32),
    csrf_token_hash BYTEA NOT NULL CHECK (octet_length(csrf_token_hash) = 32),
    user_agent VARCHAR(512) NULL,
    ip_address VARCHAR(64) NULL,
    expires_at TIMESTAMPTZ(3) NOT NULL,
    last_seen_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    revoked_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_admin_session_token UNIQUE (token_hash),
    CONSTRAINT fk_admin_session_user FOREIGN KEY (user_id) REFERENCES admin_user(id) ON DELETE CASCADE
);
CREATE INDEX idx_admin_session_user ON admin_user_session (org_id, user_id, expires_at);
CREATE INDEX idx_admin_session_expiry ON admin_user_session (expires_at) WHERE revoked_at IS NULL;

CREATE TABLE admin_platform_super_admin (
    user_id BIGINT PRIMARY KEY,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT fk_platform_admin_user FOREIGN KEY (user_id) REFERENCES admin_user(id) ON DELETE RESTRICT
);

CREATE TABLE admin_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id > 0),
    role_code VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(255) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_admin_role_org_code UNIQUE (org_id, role_code),
    CONSTRAINT uk_admin_role_org_name UNIQUE (org_id, name),
    CONSTRAINT uk_admin_role_org_id UNIQUE (org_id, id),
    CONSTRAINT ck_admin_role_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);
CREATE INDEX idx_admin_role_org_status ON admin_role (org_id, status, created_at DESC);
CREATE TRIGGER trg_admin_role_updated_at BEFORE UPDATE ON admin_role FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE admin_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(128) NOT NULL,
    resource VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    permission_type VARCHAR(16) NOT NULL,
    parent_code VARCHAR(128) NULL,
    route_path VARCHAR(255) NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_admin_permission_code UNIQUE (permission_code),
    CONSTRAINT uk_admin_permission_resource_action UNIQUE (resource, action),
    CONSTRAINT ck_admin_permission_type CHECK (permission_type IN ('MENU', 'ACTION')),
    CONSTRAINT ck_admin_permission_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);
CREATE INDEX idx_admin_permission_tree ON admin_permission (permission_type, parent_code, sort_order, id);
CREATE TRIGGER trg_admin_permission_updated_at BEFORE UPDATE ON admin_permission FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE admin_user_role (
    org_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (org_id, user_id, role_id),
    CONSTRAINT fk_admin_user_role_user FOREIGN KEY (org_id, user_id) REFERENCES admin_user(org_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_user_role_role FOREIGN KEY (org_id, role_id) REFERENCES admin_role(org_id, id) ON DELETE CASCADE
);
CREATE INDEX idx_admin_user_role_user ON admin_user_role (org_id, user_id);
CREATE INDEX idx_admin_user_role_role ON admin_user_role (org_id, role_id);

CREATE TABLE admin_role_permission (
    org_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (org_id, role_id, permission_id),
    CONSTRAINT fk_admin_role_permission_role FOREIGN KEY (org_id, role_id) REFERENCES admin_role(org_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_role_permission_permission FOREIGN KEY (permission_id) REFERENCES admin_permission(id) ON DELETE RESTRICT
);
CREATE INDEX idx_admin_role_permission_role ON admin_role_permission (org_id, role_id);

-- 后台菜单与操作使用稳定编码；后端授权和前端展示共用这些编码。
INSERT INTO admin_permission (permission_code, resource, action, permission_type, route_path, sort_order)
VALUES
 ('dashboard.view', 'dashboard', 'view', 'MENU', '/', 10),
 ('catalog.sku.view', 'catalog.sku', 'view', 'MENU', '/catalog/skus', 20),
 ('catalog.sku.create', 'catalog.sku', 'create', 'ACTION', NULL, 21),
 ('catalog.sku.update', 'catalog.sku', 'update', 'ACTION', NULL, 22),
 ('catalog.sku.publish', 'catalog.sku', 'publish', 'ACTION', NULL, 23),
 ('catalog.category.view', 'catalog.category', 'view', 'MENU', '/catalog/categories', 30),
 ('catalog.category.manage', 'catalog.category', 'manage', 'ACTION', NULL, 31),
 ('order.view', 'order', 'view', 'MENU', '/orders', 40),
 ('order.confirm', 'order', 'confirm', 'ACTION', NULL, 41),
 ('fulfillment.view', 'fulfillment', 'view', 'MENU', '/work-orders', 50),
 ('fulfillment.dispatch', 'fulfillment', 'dispatch', 'ACTION', NULL, 51),
 ('fulfillment.reassign', 'fulfillment', 'reassign', 'ACTION', NULL, 52),
 ('fulfillment.reschedule', 'fulfillment', 'reschedule', 'ACTION', NULL, 53),
 ('fulfillment.qa_review', 'fulfillment', 'qa_review', 'ACTION', NULL, 54),
 ('fulfillment.director_review', 'fulfillment', 'director_review', 'ACTION', NULL, 55),
 ('fulfillment.customer_service', 'fulfillment', 'customer_service', 'ACTION', NULL, 56),
 ('worker.view', 'worker', 'view', 'MENU', '/workers', 60),
 ('worker.manage', 'worker', 'manage', 'ACTION', NULL, 61),
 ('worker.skill.view', 'worker.skill', 'view', 'MENU', '/worker-skills', 70),
 ('worker.skill.manage', 'worker.skill', 'manage', 'ACTION', NULL, 71),
 ('media.manage', 'media', 'manage', 'ACTION', NULL, 80),
 ('admin.user.view', 'admin.user', 'view', 'MENU', '/settings/users', 90),
 ('admin.user.create', 'admin.user', 'create', 'ACTION', NULL, 91),
 ('admin.user.update', 'admin.user', 'update', 'ACTION', NULL, 92),
 ('admin.user.disable', 'admin.user', 'disable', 'ACTION', NULL, 93),
 ('admin.user.reset_password', 'admin.user', 'reset_password', 'ACTION', NULL, 94),
 ('admin.role.view', 'admin.role', 'view', 'MENU', '/settings/roles', 100),
 ('admin.role.create', 'admin.role', 'create', 'ACTION', NULL, 101),
 ('admin.role.update', 'admin.role', 'update', 'ACTION', NULL, 102),
 ('admin.role.assign_permission', 'admin.role', 'assign_permission', 'ACTION', NULL, 103),
 ('admin.role.delete', 'admin.role', 'delete', 'ACTION', NULL, 104),
 ('audit.view', 'audit', 'view', 'ACTION', NULL, 110)
ON CONFLICT (permission_code) DO UPDATE
SET resource = EXCLUDED.resource, action = EXCLUDED.action,
    permission_type = EXCLUDED.permission_type, route_path = EXCLUDED.route_path,
    sort_order = EXCLUDED.sort_order, updated_at = CURRENT_TIMESTAMP(3);

-- 每个现有租户创建内置租户管理员角色并绑定当前权限目录。
INSERT INTO admin_role (org_id, role_code, name, description, status, is_builtin)
SELECT o.id, 'tenant_admin', '租户管理员', '拥有本租户全部后台权限', 'ACTIVE', TRUE
FROM organization o
ON CONFLICT (org_id, role_code) DO NOTHING;

INSERT INTO admin_role_permission (org_id, role_id, permission_id)
SELECT r.org_id, r.id, p.id
FROM admin_role r
JOIN admin_permission p ON p.status = 'ACTIVE'
WHERE r.role_code = 'tenant_admin'
ON CONFLICT DO NOTHING;
