ALTER TABLE work_order
    ADD COLUMN IF NOT EXISTS visit_status VARCHAR(48) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS customer_acceptance_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS customer_acceptance_source VARCHAR(16) NULL,
    ADD COLUMN IF NOT EXISTS customer_acceptance_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN IF NOT EXISTS internal_review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_QA',
    ADD COLUMN IF NOT EXISTS closure_status VARCHAR(48) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS completion_outcome VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS completion_submission_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN IF NOT EXISTS auto_accept_due_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN IF NOT EXISTS customer_service_confirmation_id BIGINT NULL;

UPDATE work_order
SET visit_status = CASE WHEN status = 'FINISHED' THEN 'FINISHED' ELSE 'OPEN' END,
    customer_acceptance_status = CASE WHEN status = 'FINISHED' THEN 'MANUAL_ACCEPTED' ELSE 'PENDING' END,
    internal_review_status = CASE WHEN status = 'FINISHED' THEN 'APPROVED' ELSE 'PENDING_QA' END,
    closure_status = CASE WHEN status = 'FINISHED' THEN 'FINISHED' ELSE 'OPEN' END,
    completion_outcome = CASE WHEN status = 'FINISHED' THEN 'NORMAL' ELSE NULL END
WHERE TRUE;

CREATE TABLE IF NOT EXISTS completion_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
    worker_id BIGINT NOT NULL CHECK (worker_id >= 0),
    summary VARCHAR(1000) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED',
    submitted_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_completion_submission_attempt UNIQUE (org_id, work_order_id, attempt_no)
);
CREATE INDEX IF NOT EXISTS idx_completion_submission_work_order ON completion_submission(org_id, work_order_id, submitted_at DESC);

CREATE TABLE IF NOT EXISTS customer_acceptance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    submission_id BIGINT NOT NULL CHECK (submission_id >= 0),
    customer_id BIGINT NOT NULL CHECK (customer_id >= 0),
    decision VARCHAR(16) NOT NULL CHECK (decision IN ('ACCEPT','REJECT')),
    source VARCHAR(16) NOT NULL CHECK (source IN ('MANUAL','AUTO')),
    reason VARCHAR(512) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_customer_acceptance_submission UNIQUE (org_id, submission_id)
);

CREATE TABLE IF NOT EXISTS customer_rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    submission_id BIGINT NOT NULL CHECK (submission_id >= 0),
    customer_id BIGINT NOT NULL CHECK (customer_id >= 0),
    stars INTEGER NOT NULL CHECK (stars BETWEEN 1 AND 5),
    content VARCHAR(1000) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_customer_rating_submission UNIQUE (org_id, submission_id)
);

CREATE TABLE IF NOT EXISTS internal_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    submission_id BIGINT NOT NULL CHECK (submission_id >= 0),
    level VARCHAR(16) NOT NULL CHECK (level IN ('QA','DIRECTOR')),
    decision VARCHAR(16) NOT NULL CHECK (decision IN ('APPROVE','REJECT')),
    reviewer_id BIGINT NOT NULL CHECK (reviewer_id >= 0),
    note VARCHAR(512) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_internal_review_work_order ON internal_review(org_id, work_order_id, created_at);

CREATE TABLE IF NOT EXISTS customer_service_confirmation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    decision VARCHAR(32) NOT NULL CHECK (decision IN ('SECOND_VISIT_REQUIRED','NO_SECOND_VISIT')),
    note VARCHAR(512) NULL,
    operator_id BIGINT NOT NULL CHECK (operator_id >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_customer_service_confirmation_work_order UNIQUE (org_id, work_order_id)
);

CREATE TABLE IF NOT EXISTS work_order_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    event_code VARCHAR(64) NOT NULL,
    operator_type VARCHAR(32) NOT NULL,
    operator_id BIGINT NOT NULL DEFAULT 0 CHECK (operator_id >= 0),
    note VARCHAR(512) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_work_order_event_timeline ON work_order_event(org_id, work_order_id, created_at, id);

ALTER TABLE work_order
    ADD CONSTRAINT fk_work_order_customer_service_confirmation
    FOREIGN KEY (customer_service_confirmation_id) REFERENCES customer_service_confirmation(id) NOT VALID;
