ALTER TABLE customer_order
    ADD COLUMN confirmed_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN completed_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN cancelled_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN cancel_reason VARCHAR(512) NULL;

CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    order_id BIGINT NOT NULL CHECK (order_id >= 0),
    from_status VARCHAR(48) NULL,
    to_status VARCHAR(48) NOT NULL,
    event_code VARCHAR(64) NOT NULL,
    operator_type VARCHAR(32) NOT NULL,
    operator_id BIGINT NOT NULL DEFAULT 0 CHECK (operator_id >= 0),
    operator_name VARCHAR(64) NOT NULL DEFAULT 'system',
    reason VARCHAR(512) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX idx_order_status_history_order ON order_status_history (org_id, order_id, created_at, id);

ALTER TABLE employee_account
    ADD COLUMN role VARCHAR(32) NOT NULL DEFAULT 'WORKER',
    ADD COLUMN mobile VARCHAR(32) NULL;
ALTER TABLE employee_account ADD CONSTRAINT ck_employee_role CHECK (role = 'WORKER');

ALTER TABLE work_order
    ADD COLUMN accepted_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN arrived_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN started_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN completion_submitted_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN reviewed_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN finished_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN cancelled_at TIMESTAMPTZ(3) NULL,
    ADD COLUMN completion_summary VARCHAR(1000) NULL,
    ADD COLUMN review_note VARCHAR(512) NULL,
    ADD COLUMN exception_code VARCHAR(64) NULL,
    ADD COLUMN cancel_reason VARCHAR(512) NULL;

ALTER TABLE work_order_status_history
    ADD COLUMN operator_type VARCHAR(32) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN operator_name VARCHAR(64) NOT NULL DEFAULT 'system';

CREATE TABLE work_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    order_item_id BIGINT NOT NULL CHECK (order_item_id >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_work_order_item_pair UNIQUE (org_id, work_order_id, order_item_id),
    CONSTRAINT uk_order_item_primary_work_order UNIQUE (org_id, order_item_id)
);
CREATE INDEX idx_work_order_item_order ON work_order_item (org_id, order_item_id);

CREATE TABLE work_order_assignment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    from_assignee_id BIGINT NULL CHECK (from_assignee_id IS NULL OR from_assignee_id >= 0),
    to_assignee_id BIGINT NULL CHECK (to_assignee_id IS NULL OR to_assignee_id >= 0),
    from_appointment_at TIMESTAMPTZ(3) NULL,
    to_appointment_at TIMESTAMPTZ(3) NULL,
    event_code VARCHAR(64) NOT NULL,
    operator_type VARCHAR(32) NOT NULL,
    operator_id BIGINT NOT NULL DEFAULT 0 CHECK (operator_id >= 0),
    operator_name VARCHAR(64) NOT NULL DEFAULT 'system',
    reason VARCHAR(512) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX idx_assignment_history_work_order ON work_order_assignment_history (org_id, work_order_id, created_at, id);

CREATE TABLE work_order_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    media_id BIGINT NOT NULL CHECK (media_id >= 0),
    stage VARCHAR(16) NOT NULL,
    customer_visible BOOLEAN NOT NULL DEFAULT TRUE,
    uploaded_by BIGINT NOT NULL CHECK (uploaded_by >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_work_order_evidence_media UNIQUE (org_id, work_order_id, media_id),
    CONSTRAINT ck_work_order_evidence_stage CHECK (stage IN ('BEFORE', 'DURING', 'AFTER'))
);
CREATE INDEX idx_work_order_evidence_stage ON work_order_evidence (org_id, work_order_id, stage, created_at);

ALTER TABLE idempotency_record DROP CONSTRAINT uk_idempotency_principal_key;
ALTER TABLE idempotency_record ADD COLUMN principal_type VARCHAR(32) NOT NULL DEFAULT 'CUSTOMER';
ALTER TABLE idempotency_record ADD CONSTRAINT uk_idempotency_principal_key UNIQUE (org_id, principal_type, principal_id, idempotency_key);

UPDATE customer_order SET status = 'PENDING_CONFIRMATION'
WHERE status = 'WAITING_PAYMENT' AND paid_amount = 0;

INSERT INTO order_status_history (org_id, order_id, from_status, to_status, event_code, operator_type, operator_id, operator_name)
SELECT org_id, id, NULL, status, 'ORDER_MIGRATED', 'SYSTEM', 0, 'system'
FROM customer_order;
