-- PostgreSQL 18 baseline.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP(3);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CHECK (id >= 0)
);

CREATE TABLE employee_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    username VARCHAR(64) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_employee_org_username UNIQUE (org_id, username)
);
CREATE INDEX idx_employee_org_status ON employee_account (org_id, status);

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    display_name VARCHAR(64) NOT NULL,
    mobile_cipher BYTEA NULL,
    mobile_hash BYTEA NULL CHECK (mobile_hash IS NULL OR octet_length(mobile_hash) = 32),
    source_channel VARCHAR(64) NULL,
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL
);
CREATE INDEX idx_customer_org_created ON customer (org_id, created_at);
CREATE INDEX idx_customer_org_mobile_hash ON customer (org_id, mobile_hash);

CREATE TABLE service_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    parent_id BIGINT NULL CHECK (parent_id IS NULL OR parent_id >= 0),
    name VARCHAR(64) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX idx_category_org_parent_sort ON service_category (org_id, parent_id, sort_order);

CREATE TABLE service_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    category_id BIGINT NOT NULL CHECK (category_id >= 0),
    sku_code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NULL,
    service_scope VARCHAR(1000) NOT NULL,
    exclusions VARCHAR(1000) NOT NULL,
    warranty_description VARCHAR(500) NOT NULL,
    price_mode VARCHAR(32) NOT NULL,
    base_price BIGINT NOT NULL DEFAULT 0 CHECK (base_price >= 0),
    unit VARCHAR(16) NOT NULL DEFAULT '次',
    cover_media_id BIGINT NULL CHECK (cover_media_id IS NULL OR cover_media_id >= 0),
    current_published_version INTEGER NULL CHECK (current_published_version IS NULL OR current_published_version > 0),
    published_at TIMESTAMPTZ(3) NULL,
    status VARCHAR(32) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_sku_org_code UNIQUE (org_id, sku_code)
);
CREATE INDEX idx_sku_org_category_status ON service_sku (org_id, category_id, status);

CREATE TABLE customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    order_no VARCHAR(32) NOT NULL,
    customer_id BIGINT NOT NULL CHECK (customer_id >= 0),
    contact_name VARCHAR(64) NOT NULL,
    contact_mobile VARCHAR(32) NOT NULL,
    service_address VARCHAR(255) NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_amount BIGINT NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    paid_amount BIGINT NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    item_count INTEGER NOT NULL DEFAULT 0 CHECK (item_count >= 0),
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_order_no UNIQUE (order_no)
);
CREATE INDEX idx_order_org_customer_created ON customer_order (org_id, customer_id, created_at);
CREATE INDEX idx_order_org_status_created ON customer_order (org_id, status, created_at);

CREATE TABLE work_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL CHECK (order_id >= 0),
    assignee_id BIGINT NULL CHECK (assignee_id IS NULL OR assignee_id >= 0),
    status VARCHAR(48) NOT NULL,
    priority VARCHAR(16) NOT NULL,
    appointment_at TIMESTAMPTZ(3) NULL,
    sla_at TIMESTAMPTZ(3) NULL,
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_work_order_no UNIQUE (work_order_no)
);
CREATE INDEX idx_work_order_assignee_status_time ON work_order (org_id, assignee_id, status, appointment_at);
CREATE INDEX idx_work_order_status_sla ON work_order (org_id, status, sla_at);

CREATE TABLE work_order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    work_order_id BIGINT NOT NULL CHECK (work_order_id >= 0),
    from_status VARCHAR(48) NULL,
    to_status VARCHAR(48) NOT NULL,
    event_code VARCHAR(64) NOT NULL,
    operator_id BIGINT NOT NULL CHECK (operator_id >= 0),
    reason VARCHAR(512) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX idx_work_order_history ON work_order_status_history (org_id, work_order_id, created_at);

CREATE TABLE idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    principal_id BIGINT NOT NULL CHECK (principal_id >= 0),
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash BYTEA NOT NULL CHECK (octet_length(request_hash) = 32),
    response_code VARCHAR(64) NULL,
    response_body JSONB NULL,
    expires_at TIMESTAMPTZ(3) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_idempotency_principal_key UNIQUE (org_id, principal_id, idempotency_key)
);
CREATE INDEX idx_idempotency_expires ON idempotency_record (expires_at);

CREATE TABLE outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT NOT NULL CHECK (aggregate_id >= 0),
    event_type VARCHAR(128) NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL,
    available_at TIMESTAMPTZ(3) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    published_at TIMESTAMPTZ(3) NULL,
    last_error VARCHAR(1024) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX idx_outbox_status_available ON outbox_event (status, available_at);
CREATE INDEX idx_outbox_aggregate ON outbox_event (org_id, aggregate_type, aggregate_id);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    principal_id BIGINT NULL CHECK (principal_id IS NULL OR principal_id >= 0),
    action_code VARCHAR(128) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(64) NULL,
    request_id VARCHAR(64) NULL,
    ip_address VARCHAR(64) NULL,
    detail_json JSONB NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX idx_audit_org_resource ON audit_log (org_id, resource_type, resource_id, created_at);
CREATE INDEX idx_audit_request ON audit_log (request_id);

CREATE TABLE media_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    owner_type VARCHAR(32) NOT NULL,
    owner_id BIGINT NOT NULL CHECK (owner_id >= 0),
    purpose VARCHAR(32) NOT NULL,
    media_type VARCHAR(16) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(255) NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_media_object_key UNIQUE (object_key)
);
CREATE INDEX idx_media_owner ON media_asset (org_id, owner_type, owner_id, purpose);
CREATE INDEX idx_media_status_created ON media_asset (status, created_at);

CREATE TABLE service_sku_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    sku_id BIGINT NOT NULL CHECK (sku_id >= 0),
    media_id BIGINT NOT NULL CHECK (media_id >= 0),
    media_role VARCHAR(16) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_sku_media UNIQUE (org_id, sku_id, media_id)
);
CREATE INDEX idx_sku_media_role_sort ON service_sku_media (org_id, sku_id, media_role, sort_order);

CREATE TABLE service_sku_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    sku_id BIGINT NOT NULL CHECK (sku_id >= 0),
    version_no INTEGER NOT NULL CHECK (version_no > 0),
    snapshot_json JSONB NOT NULL,
    published_by VARCHAR(64) NOT NULL,
    published_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_sku_version UNIQUE (org_id, sku_id, version_no)
);
CREATE INDEX idx_sku_version_published ON service_sku_version (org_id, published_at);

CREATE TABLE shopping_cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    customer_id BIGINT NOT NULL CHECK (customer_id >= 0),
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_cart_customer UNIQUE (org_id, customer_id)
);

CREATE TABLE shopping_cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    cart_id BIGINT NOT NULL CHECK (cart_id >= 0),
    sku_id BIGINT NOT NULL CHECK (sku_id >= 0),
    sku_version INTEGER NOT NULL CHECK (sku_version > 0),
    quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    unit_price BIGINT NOT NULL CHECK (unit_price >= 0),
    fault_description VARCHAR(500) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_cart_sku_version UNIQUE (org_id, cart_id, sku_id, sku_version)
);
CREATE INDEX idx_cart_item_cart ON shopping_cart_item (org_id, cart_id);

CREATE TABLE shopping_cart_item_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    cart_item_id BIGINT NOT NULL CHECK (cart_item_id >= 0),
    media_id BIGINT NOT NULL CHECK (media_id >= 0),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_cart_item_media UNIQUE (org_id, cart_item_id, media_id)
);
CREATE INDEX idx_cart_item_media_item ON shopping_cart_item_media (org_id, cart_item_id, sort_order);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    order_id BIGINT NOT NULL CHECK (order_id >= 0),
    sku_id BIGINT NOT NULL CHECK (sku_id >= 0),
    sku_version INTEGER NOT NULL CHECK (sku_version > 0),
    sku_code_snapshot VARCHAR(64) NOT NULL,
    sku_name_snapshot VARCHAR(128) NOT NULL,
    unit_snapshot VARCHAR(16) NOT NULL,
    service_scope_snapshot VARCHAR(1000) NOT NULL,
    exclusions_snapshot VARCHAR(1000) NOT NULL,
    warranty_snapshot VARCHAR(500) NOT NULL,
    sku_cover_media_id_snapshot BIGINT NULL CHECK (sku_cover_media_id_snapshot IS NULL OR sku_cover_media_id_snapshot >= 0),
    fault_description VARCHAR(500) NOT NULL,
    unit_price BIGINT NOT NULL CHECK (unit_price >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    subtotal_amount BIGINT NOT NULL CHECK (subtotal_amount >= 0),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX idx_order_item_order ON order_item (org_id, order_id);

CREATE TABLE order_item_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL CHECK (org_id >= 0),
    order_item_id BIGINT NOT NULL CHECK (order_item_id >= 0),
    media_id BIGINT NOT NULL CHECK (media_id >= 0),
    media_type VARCHAR(16) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_order_item_media UNIQUE (org_id, order_item_id, media_id)
);
CREATE INDEX idx_order_item_media_item ON order_item_media (org_id, order_item_id, sort_order);

CREATE TRIGGER trg_organization_updated_at BEFORE UPDATE ON organization FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_employee_account_updated_at BEFORE UPDATE ON employee_account FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_customer_updated_at BEFORE UPDATE ON customer FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_service_category_updated_at BEFORE UPDATE ON service_category FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_service_sku_updated_at BEFORE UPDATE ON service_sku FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_customer_order_updated_at BEFORE UPDATE ON customer_order FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_work_order_updated_at BEFORE UPDATE ON work_order FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_shopping_cart_updated_at BEFORE UPDATE ON shopping_cart FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_shopping_cart_item_updated_at BEFORE UPDATE ON shopping_cart_item FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO organization (id, name, status) VALUES (1, 'FixPro Local', 'ACTIVE');
INSERT INTO customer (id, org_id, display_name, source_channel) VALUES (1, 1, '本地演示客户', 'LOCAL');
INSERT INTO service_category (id, org_id, parent_id, name, sort_order, status) VALUES
    (1001, 1, NULL, '精准测漏', 10, 'ACTIVE'),
    (1002, 1, NULL, '水路维修', 20, 'ACTIVE'),
    (1003, 1, NULL, '防水维修', 30, 'ACTIVE'),
    (1004, 1, NULL, '暖气净水维保', 40, 'ACTIVE');

SELECT setval(pg_get_serial_sequence('organization', 'id'), 1, true);
SELECT setval(pg_get_serial_sequence('customer', 'id'), 1, true);
SELECT setval(pg_get_serial_sequence('service_category', 'id'), 1004, true);
