root = "."
tmp_dir = ".tmp/air"

[build]
cmd = "go build -o ./.tmp/air/fixpro-server-dev ./cmd/server"
entrypoint = ["./.tmp/air/fixpro-server-dev"]
include_ext = ["go"]
exclude_dir = ["bin", ".tmp", "vendor", "testdata", "docs", "db"]
exclude_regex = ["_test\\.go$"]
exclude_unchanged = true
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500
log = "air-errors.log"

[build.windows]
cmd = "go build -o ./.tmp/air/fixpro-server-dev.exe ./cmd/server"
entrypoint = [".tmp\\air\\fixpro-server-dev.exe"]

[log]
time = true

[misc]
clean_on_exit = true
startup_banner = ""

[screen]
clear_on_rebuild = false
keep_scroll = true
